[WIP]  Front/loggin space
luctst/blacklist pull request #1
Opened 2020-01-20 17:18 UTC by Kvin3324

## SpaceLog page

Front for the spaceLog space.

2020-01-21 18:19 UTC, luctst requested changes

2020-01-21 18:19 UTC, luctst commented on client/src/components/App.js
> +      <div className="App">
Tu peux enlever cette div ou pas ?

2020-01-21 18:19 UTC, luctst commented on client/src/components/App.js
> +      <div className="App">
@Kvin3324

2020-01-21 18:19 UTC, luctst commented on client/src/components/App.js
> +        <div className="container" style={{display: "flex", justifyContent: "center"}}>
Pareille pour celle-la y'a pas moyen de l'enlever ? @Kvin3324

2020-01-21 18:19 UTC, luctst commented on client/src/components/App.js
> +          <Route exact path="/inscription" component={SpaceLog} />
Il faut içi qu'une seule route. `<Route  exact path=["/", "/inscription"] component={SpaceLog}/>`

2020-01-21 18:19 UTC, luctst commented on client/src/components/BlackList/BlackList.js
> +    <BlackListStyled className="container my--blacklist mt-3">
Utilise une `section` plutôt

2020-01-21 18:19 UTC, luctst commented on client/src/components/BlackList/BlackList.js
> +      <li>Cloé</li>
Il faut ajouter un `ul`

2020-01-21 18:19 UTC, luctst commented on client/src/components/Header/Title.js
> +      <TitleStyled className="header--title mt-5">
Pas de div içi non plus tu peux juste laisser un h1

2020-01-22 11:11 UTC, Kvin3324 commented on client/src/components/App.js
> +      <div className="App">
Corrected: e624bfc

2020-01-22 11:11 UTC, Kvin3324 commented on client/src/components/App.js
> +        <div className="container" style={{display: "flex", justifyContent: "center"}}>
Corrected: e624bfc

2020-01-22 11:11 UTC, Kvin3324 commented on client/src/components/App.js
> +          <Route exact path="/inscription" component={SpaceLog} />
Corrected: e624bfc

2020-01-22 11:11 UTC, Kvin3324 commented on client/src/components/BlackList/BlackList.js
> +      <li>Cloé</li>
Corrected: 3d0aaff

2020-01-22 11:12 UTC, Kvin3324 commented on client/src/components/BlackList/BlackList.js
> +    <BlackListStyled className="container my--blacklist mt-3">
Corrected: f8ab22f

2020-01-22 11:12 UTC, Kvin3324 commented on client/src/components/Header/Title.js
> +      <TitleStyled className="header--title mt-5">
Corrected: 649026a

2020-01-22 14:01 UTC, luctst approved these changes

2020-01-22 14:35 UTC, luctst requested changes

2020-01-22 14:35 UTC, luctst commented on client/src/components/BlackList/BlackList.js
> +            <ul>
Only `<li>`here

2020-01-22 14:35 UTC, luctst commented on client/src/components/SpaceLog/SpaceLog.js
> +          <button className="btn btn-primary">Submit</button>
Remplacer par un `<input type="submit"/>`

2020-01-22 14:35 UTC, luctst commented on client/src/components/BlackList/BlackList.js
> +      newState.name = inputNameValue.current.value;
Modifier `newState` n'est plus un objet

2020-01-22 14:35 UTC, luctst commented on client/src/components/BlackList/BlackList.js
> +            <ul>
Il faut aussi avoir la possibilité d'éditer et de supprimer un `<li>`

2020-01-22 15:08 UTC, luctst requested changes

2020-01-22 15:08 UTC, luctst commented on client/src/components/BlackList/BlackList.js
>        newState.name = inputNameValue.current.value;
Erreur here

2020-01-23 09:52 UTC, luctst approved these changes

2020-01-23 09:52 UTC, merged